-- 코드를 작성해주세요
/*
1. ITEM_ID = PARENT_ITEM_ID : JOIN
2. JOIN한 ITEM_TREE의 ITEM_ID를 조회
*/
-- 1안 : 서브쿼리 사용용
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT T.ITEM_ID
    FROM ITEM_INFO I RIGHT JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE I.RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC;

-- 2안 : ROOT 아이템이 아닌 경우만 뽑아서 출력
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID DESC;